// scripts/generate-fcm-sw.js
const fs = require('fs');
const path = require('path');

const apiKey = process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '';
const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '';
const messagingSenderId = process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '';
const appId = process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '';

const allKeysPresent = apiKey && projectId && messagingSenderId && appId;

if (!allKeysPresent) {
  console.warn('One or more NEXT_PUBLIC_FIREBASE_* env variables are missing.');
  console.log('Writing an empty firebase-messaging-sw.js file. Push notifications will be disabled.');
}

const authDomain = projectId ? `${projectId}.firebaseapp.com` : '';
const storageBucket = projectId ? `${projectId}.appspot.com` : '';

const swContent = `
// This file is auto-generated by scripts/generate-fcm-sw.js

importScripts('https://www.gstatic.com/firebasejs/9.22.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.22.1/firebase-messaging-compat.js');

const firebaseConfig = {
  apiKey: "${apiKey}",
  authDomain: "${authDomain}",
  projectId: "${projectId}",
  storageBucket: "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId: "${appId}"
};

try {
  // Only initialize if all keys are present
  if (firebaseConfig.apiKey && firebaseConfig.projectId) {
    firebase.initializeApp(firebaseConfig);
    const messaging = firebase.messaging();

    messaging.onBackgroundMessage(function(payload) {
      console.log('[firebase-messaging-sw.js] Received background message ', payload);
      const notificationTitle = payload.notification?.title || 'Notificare Nouă';
      const notificationOptions = {
        body: payload.notification?.body || 'Ai primit o notificare nouă.',
        icon: '/icon.svg'
      };
      self.registration.showNotification(notificationTitle, notificationOptions);
    });
  }
} catch (e) {
    console.error('Error initializing Firebase in Service Worker:', e);
}
`;

fs.writeFileSync(path.join(process.cwd(), 'public', 'firebase-messaging-sw.js'), swContent, 'utf8');
console.log('Successfully generated public/firebase-messaging-sw.js');
